### ISSUE TITLE
Deepen our knowledge of the ECS pattern

### ISSUE THREAD

**Issue by giacomocavalieri** [nicolasfara/ecscala#13]
**Initial estimate of effort:** 20

#### Sprint tasks
- [x] #14
- [x] #15
- [x] #16

#### Additional resources
- [Skypjack's blog](https://skypjack.github.io)
- [Guru99's guide](https://www.guru99.com/entity-component-system.html)

**Comment by vitlinda** [comment]
**Remaining effort:** 0
